version: 2.1

executors:
  maven:
    docker:
      - image: cimg/openjdk:17.0
      - image: cimg/postgres:14.12

jobs:
  build:
    executor: maven
    steps:
      - checkout
      - run:
          name: Java version
          command: java --version
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - run:
          name: Build Project
          command: mvn test
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
